"""Criação inicial das tabelas

Revision ID: 6ed31a9d20c1
Revises: 
Create Date: 2025-01-22 10:49:43.538880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ed31a9d20c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doacoes')
    op.drop_table('pessoas')
    op.drop_table('produtos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doacoes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pessoa_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('produto_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantidade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('data_doacao', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name='doacoes_ibfk_1'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name='doacoes_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('produtos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome_produto', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('quantidade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('data_entrada', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pessoas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('endereco', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bairro', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('telefone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('filhos', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('profissao', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('qtd_pessoas', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('locomocao', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_cadastro', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
